language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.26"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
script:
  - prove -lv $(test-dirs)   # parallel testing
